[settings]
lockfile = true
lockfile_platforms = ["macos-arm64"]
idiomatic_version_file_enable_tools = ["node", "pnpm", "yarn"]

[tools]
node = "24"
pnpm = "12"
go = "1.27"
python = "3.14"
java = "27"
uv = "latest"

"aqua:LuaLS/lua-language-server" = "latest"
"aqua:atuinsh/atuin" = "latest"
"aqua:rust-lang/rust-analyzer" = "latest"
"aqua:tealdeer-rs/tealdeer" = "latest"
"aqua:sharkdp/bat" = "latest"
"aqua:carapace-sh/carapace-bin" = "latest"
"aqua:wagoodman/dive" = "latest"
"aqua:sharkdp/fd" = "latest"
"aqua:junegunn/fzf" = "latest"
"aqua:cli/cli" = "latest"
"aqua:dandavison/delta" = "latest"
"aqua:jj-vcs/jj" = "latest"
"aqua:jqlang/jq" = "latest"
"aqua:casey/just" = "latest"
"aqua:kubernetes/kubernetes/kubectl" = "latest"
"aqua:FiloSottile/mkcert" = "latest"
"aqua:rclone/rclone" = "latest"
"aqua:linebender/resvg" = "latest"
"aqua:koalaman/shellcheck" = "latest"
"aqua:sxyazi/yazi" = "latest"
"aqua:getzola/zola" = "latest"
"aqua:ajeetdsouza/zoxide" = "latest"
"npm:typescript" = "6"
"npm:typescript-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:yaml-language-server" = "latest"
"npm:svelte-language-server" = { version = "latest", trust_policy_excludes = ["svelte@4.2.20"] }
"npm:bash-language-server" = "latest"
"pipx:python-lsp-server" = "latest"

[bootstrap.user]
login_shell = "/opt/homebrew/bin/nu"

[bootstrap.packages]
"brew:borgbackup" = "latest"
"brew:borgmatic" = "latest"
"brew:cloudflare-speed-cli" = "latest"
"brew:editorconfig" = "latest"
"brew:exiftool" = "latest"
"brew:ffmpeg-full" = "latest"
"brew:gnupg" = "latest"
"brew:httpie" = "latest"
"brew:imagemagick-full" = "latest"
"brew:jnsahaj/lumen/lumen" = "latest"
"brew:keinzirp/kakoune/kakoune-patched" = "latest"
"brew:mdcat" = "latest"
"brew:nushell" = "latest"
"brew:openjdk" = "latest"
"brew:overmind" = "latest"
"brew:pgcli" = "latest"
"brew:pinentry-mac" = "latest"
"brew:postgresql@18" = "latest"
"brew:ranger" = "latest"
"brew:rm-improved" = "latest"
"brew:rust" = "latest"
"brew:scc" = "latest"
"brew:stow" = "latest"
"brew:timewarrior" = "latest"
"brew:watchman" = "latest"
"brew:zellij" = "latest"

"brew-cask:alt-tab" = "latest"
"brew-cask:android-platform-tools" = "latest"
"brew-cask:anki" = "latest"
"brew-cask:colemak-dh" = "latest"
"brew-cask:font-fira-code" = "latest"
"brew-cask:font-iosevka" = "latest"
"brew-cask:font-liberation-nerd-font" = "latest"
"brew-cask:font-symbols-only-nerd-font" = "latest"
"brew-cask:font-terminess-ttf-nerd-font" = "latest"
"brew-cask:gimp" = "latest"
"brew-cask:hiddenbar" = "latest"
"brew-cask:keepassxc" = "latest"
"brew-cask:meld" = "latest"
"brew-cask:music-decoy" = "latest"
"brew-cask:openlogi" = "latest"
"brew-cask:orbstack" = "latest"
"brew-cask:sol" = "latest"
"brew-cask:stats" = "latest"
"brew-cask:switch" = "latest"
"brew-cask:vlc" = "latest"
"brew-cask:waterfox" = "latest"
"brew-cask:whatcable" = "latest"
