[ui]
editor = "kak"
pager = "delta"
diff-formatter = ":git"
default-command = ["status"]
diff-editor = "meld"
merge-editor = "meld"

[user]
name = "keinzirp"
email = "keinzirp@gmail.com"

[[--scope]]
--when.repositories = ["~/Development/Work"]
[--scope.user]
email = "andreas@rough.app"

[signing]
behavior = "own"
backend = "gpg"

[aliases]
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]
mine = ["bookmark", "list", "-r", "mine()"]
jj = ["util", "exec", "--", "jj"]

[templates]
draft_commit_description = '''
  concat(
    coalesce(description, default_commit_description, "\n"),
    surround(
      "\nJJ: This commit contains the following changes:\n", "",
      indent("JJ:     ", diff.stat(142)),
    ),
    "\nJJ: ignore-rest\n",
    diff.git(),
  )
'''
