config-version = 2
after-startup-command = []
start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 0
default-root-container-layout = 'tiles'
default-root-container-orientation = 'vertical'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
automatically-unhide-macos-hidden-apps = true
persistent-workspaces = ["1", "2", "3", "4", "5", "6", "7", "8", "9"]
on-mode-changed = []

[key-mapping]
preset = 'colemak'

[gaps]
inner.horizontal = 0
inner.vertical = 0
outer.left = 0
outer.bottom = 0
outer.top = 0
outer.right = 0

[mode.main.binding]
alt-enter = 'mode wm'

[mode.wm.binding]
alt-enter = 'mode main'
space = ['layout tiles accordion', 'mode main']
slash = ['layout tiles horizontal vertical', 'mode main']
comma = ['layout accordion horizontal vertical', 'mode main']

m = ['focus --boundaries-action wrap-around-the-workspace left', 'mode main']
j = ['focus --boundaries-action wrap-around-the-workspace down', 'mode main']
k = ['focus --boundaries-action wrap-around-the-workspace up', 'mode main']
l = ['focus --boundaries-action wrap-around-the-workspace right', 'mode main']
shift-m = ['move left', 'mode main']
shift-j = ['move down', 'mode main']
shift-k = ['move up', 'mode main']
shift-l = ['move right', 'mode main']

minus = ['resize smart -50', 'mode main']
equal = ['resize smart +50', 'mode main']
s = ['exec-and-forget screencapture -i -c', 'mode main']

1 = ['workspace 1', 'mode main']
2 = ['workspace 2', 'mode main']
3 = ['workspace 3', 'mode main']
4 = ['workspace 4', 'mode main']
5 = ['workspace 5', 'mode main']
6 = ['workspace 6', 'mode main']
7 = ['workspace 7', 'mode main']
8 = ['workspace 8', 'mode main']
9 = ['workspace 9', 'mode main']
shift-1 = ['move-node-to-workspace 1', 'mode main']
shift-2 = ['move-node-to-workspace 2', 'mode main']
shift-3 = ['move-node-to-workspace 3', 'mode main']
shift-4 = ['move-node-to-workspace 4', 'mode main']
shift-5 = ['move-node-to-workspace 5', 'mode main']
shift-6 = ['move-node-to-workspace 6', 'mode main']
shift-7 = ['move-node-to-workspace 7', 'mode main']
shift-8 = ['move-node-to-workspace 8', 'mode main']
shift-9 = ['move-node-to-workspace 9', 'mode main']

semicolon = 'mode service'
esc = 'mode main'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main']
f = ['layout floating tiling', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']
m = ['join-with left', 'mode main']
j = ['join-with down', 'mode main']
k = ['join-with up', 'mode main']
l = ['join-with right', 'mode main']
