[[mgr.prepend_keymap]]
on = "<Enter>"
run = "plugin smart-enter"
desc = "Enter directory or open file"

[[mgr.prepend_keymap]]
on = "z"
run = "plugin repo-fzf"
desc = "Fuzzy find from repository root"
