[mgr]
marker_symbol = ">"
border_symbol = "|"
border_style = { fg = "gray" }

[indicator]
padding = { open = " ", close = " " }

[tabs]
active = { reversed = true }
inactive = {}
sep_inner = { open = "[", close = "]" }
sep_outer = { open = "", close = "" }

[status]
sep_left = { open = "[", close = "]" }
sep_right = { open = "[", close = "]" }

[which]
separator = " -> "

[filetype]
rules = [
  { url = "*/", fg = "blue" },
]

[icon]
globs = []
dirs = []
files = []
exts = []
conds = []

[notify]
icon_info = ""
icon_warn = ""
icon_error = ""

[cmp]
icon_file = ""
icon_folder = ""
icon_command = ""
