db_path = "~/.local/share/atuin/history.db"
session_path = "~/.local/share/atuin/session"
filter_mode = "global"
workspaces = true
style = "full"
inline_height = 30
invert = false
show_preview = true
secrets_filter = true
enter_accept = true
search_mode = "daemon-fuzzy"
keymap_mode = "auto"

history_filter = [
  "^export .*=",
  '^\$env\.',
  '^load-env\b',
  "^ ",
]

[stats]
common_subcommands = [
  "apt",
  "cargo",
  "composer",
  "dnf",
  "docker",
  "dotnet",
  "git",
  "go",
  "ip",
  "jj",
  "kubectl",
  "nix",
  "nmcli",
  "npm",
  "pecl",
  "pnpm",
  "podman",
  "port",
  "systemctl",
  "tmux",
  "yarn",
]

[sync]
records = true

[daemon]
enabled = true
autostart = true

[ui]
columns = ["exit", "duration", "time", "directory", "command"]
