set-option global scrolloff 4,4
set-option global idle_timeout 300
set-option global tabstop 4
set-option global indentwidth 4
set-option global grepcmd 'rg --vimgrep --smart-case'
set-option global modelinefmt '%val{bufname} %val{cursor_line}:%val{cursor_char_column} {{context_info}} {{mode_info}}'
set-option global ui_options terminal_assistant=none terminal_enable_mouse=true terminal_set_title=false

hook global KakBegin .* %{
    evaluate-commands %sh{
        if command -v kak-tree-sitter >/dev/null; then
            kak-tree-sitter --init "$kak_session" --kakoune --daemonize --server --with-highlighting --with-text-objects
        fi
    }
    colorscheme base16-default-dark-treesitter
}
hook global BufCreate .*\.nu %{ set-option buffer filetype nu }

add-highlighter global/ number-lines -hlcursor
add-highlighter global/ show-matching -previous
add-highlighter global/ show-whitespaces -spc '.' -tab '>' -nbsp '~' -lf '' -only-trailing
add-highlighter global/ column 80 default,default+F
add-highlighter global/ wrap -word -indent

map global insert <c-[> <esc> -docstring 'Leave insert mode'
map global user t ':enter-user-mode tree-sitter<ret>' -docstring 'Enter Tree-sitter mode'
map global object e '<a-;>tree-sitter-object-text-objects xml-element<ret>' -docstring 'HTML element (tree-sitter)'

declare-option -hidden str next_occurrence_origin
define-command add-next-occurrence -docstring 'Select the word or add its next occurrence' %{
    set-option local next_occurrence_origin "%val{selections_desc}"
    evaluate-commands %sh{
        if [ "$kak_selection_count" -eq 1 ] && [ "$kak_selection_length" -eq 1 ]; then
            echo "execute-keys '<a-i>w'"
        fi
    }
    evaluate-commands %sh{
        keys='*N'
        [ "$kak_selections_desc" != "$kak_opt_next_occurrence_origin" ] && keys='*'
        printf "execute-keys -with-hooks -save-regs '' '%s'\n" "$keys"
    }
}
map global normal <c-n> ':add-next-occurrence<ret>' -docstring 'Select the word or add its next occurrence'

declare-user-mode user-nu
map global user n ':enter-user-mode user-nu<ret>' -docstring 'Enter Nushell mode'
map global user-nu p "|nu --stdin -c '$in | '<left>" -docstring 'Pipe selections and replace with output'
map global user-nu d "<a-|>nu --stdin -c '$in | '<left>" -docstring 'Pipe selections and discard output'
map global user-nu i "!nu -c ''<left>" -docstring 'Insert command output'
map global user-nu a "<a-!>nu -c ''<left>" -docstring 'Append command output'
map global user-nu f "$nu --stdin -c '$in | '<left>" -docstring 'Keep selections when the command succeeds'

define-command -hidden git-refresh-diff %{ evaluate-commands %sh{
    git -C "${kak_buffile%/*}" ls-files --error-unmatch -- "$kak_buffile" >/dev/null 2>&1 &&
        echo 'git show-diff'
}}
hook global WinCreate .* git-refresh-diff
hook global BufWritePost .* git-refresh-diff
hook global BufReload .* git-refresh-diff

declare-user-mode user-git
map global user g ':enter-user-mode user-git<ret>' -docstring 'Enter Git mode'
map global user-git s ':git status<ret>' -docstring 'Show Git status'
map global user-git d ':git diff<ret>' -docstring 'Show Git diff'
map global user-git b ':git blame<ret>' -docstring 'Show Git blame'
map global user-git n ':git next-hunk<ret>' -docstring 'Go to next hunk'
map global user-git p ':git prev-hunk<ret>' -docstring 'Go to previous hunk'
nop %sh{
    plug="$kak_config/plugins/plug.kak"
    [ -d "$plug" ] || git clone -q https://github.com/andreyorst/plug.kak.git "$plug" >&2
}
source "%val{config}/plugins/plug.kak/rc/plug.kak"
set-option global plug_always_ensure true
plug "andreyorst/plug.kak" noload
plug "greenfork/active-window.kak"
plug "delapouite/kakoune-buffers" config %{
    map global user b ':enter-buffers-mode<ret>' -docstring 'Enter buffer mode'
    map global user B ':enter-user-mode -lock buffers<ret>' -docstring 'Enter locked buffer mode'
}
map global user c ':comment-line<ret>' -docstring 'Toggle comments'
map global user s ':grep<space>' -docstring 'Search project contents'

plug "andreyorst/fzf.kak" config %{
    map global user f ':fzf-mode<ret>' -docstring 'Enter fzf mode'
    hook global ModuleLoaded fzf %{
        map global fzf 'F' '<esc>:fzf-buffer-files<ret>' -docstring 'Open files in the buffer directory'
    }
} defer fzf %{
    set-option global fzf_default_opts '--color=dark --bind=ctrl-/:toggle-preview'
    set-option global fzf_terminal_command 'picker-terminal kak -c %val{session} -e "%arg{@}"'
    set-option global fzf_highlight_command 'bat'
    set-option global fzf_preview_height '40%'
    # Avoid fzf-file buffile-dir's unquoted paths; rg emits full paths here.
    define-command fzf-buffer-files -docstring 'Open files in the buffer directory' %{
        fzf -preview -kak-cmd 'edit -existing' -fzf-args "-m --expect %opt{fzf_window_map},%opt{fzf_vertical_map},%opt{fzf_horizontal_map}" -items-cmd %sh{
            dir=$(dirname "$kak_buffile")
            printf "rg -L --hidden --files -- '%s'" "$(printf '%s' "$dir" | sed "s/'/'\\\\''/g")"
        }
    }
} defer fzf-file %{
    set-option global fzf_file_command 'rg'
} defer fzf-grep %{
    set-option global fzf_grep_command 'rg'
    set-option global fzf_grep_preview_command 'bat'
}

declare-option -hidden str picker_title fzf

define-command -hidden picker-zellij -params 1.. %{
    zellij-run "--floating --name %opt{picker_title} --close-on-exit --block-until-exit --width 94%% --height 90%%" %arg{@}
    zellij-action hide-floating-panes
}

define-command -hidden picker-terminal -params 1.. %{ evaluate-commands %sh{
    [ "$1" = kak ] || echo 'alias local zellij-terminal-window picker-zellij'
    echo 'terminal %arg{@}'
}}

define-command yazi-open -docstring 'Open files with Yazi' %{
    set-option local picker_title Yazi
    picker-terminal sh -c %{
        chooser=$(mktemp -t kak-yazi.XXXXXX) || exit 1
        trap 'rm -f "$chooser"' EXIT
        target=$3
        [ -e "$target" ] || target=$PWD
        yazi "$target" --chooser-file="$chooser" || exit

        kakquote() { printf '%s' "$1" | sed "s/'/''/g; 1s/^/'/; \$s/\$/'/"; }
        command=$(while IFS= read -r selected || [ -n "$selected" ]; do
            if [ "${selected#search://}" != "$selected" ]; then
                selected=$(printf '%s\n' "$selected" | sed 's,^search://[^/]*/,,' )
            fi
            [ -n "$selected" ] && printf 'edit -existing %s\n' "$(kakquote "$selected")"
        done < "$chooser")
        [ -n "$command" ] || exit 0
        printf 'evaluate-commands -client %s %s\n' \
            "$(kakquote "$1")" "$(kakquote "$command")" | kak -p "$2"
    } yazi-open %val{client} %val{session} %val{buffile}
}
map global user y ':yazi-open<ret>' -docstring 'Open files with Yazi'

plug "lePerdu/kakboard" config %{
    hook global WinCreate .* %{ kakboard-enable }
}

plug "andreyorst/smarttab.kak" defer smarttab %{
    set-option global softtabstop 4
} config %{
    hook global BufOpenFile .* %{ try %{ editorconfig-load }; autoconfigtab }
    hook global BufNewFile .* %{ try %{ editorconfig-load }; autoconfigtab }
}

plug "kak-lsp/kak-lsp" do %{
    cargo install --locked --force --path .
} config %{
    set-option global modelinefmt "%opt{lsp_modeline} %opt{modelinefmt}"
    set-option global lsp_diagnostic_line_error_sign 'E'
    set-option global lsp_diagnostic_line_warning_sign 'W'
    set-option global lsp_diagnostic_line_info_sign 'I'
    set-option global lsp_diagnostic_line_hint_sign 'H'
    set-option global lsp_hover_anchor false
    set-option global lsp_auto_show_code_actions true
    set-option global lsp_completion_trigger fail

    hook global BufSetOption filetype=nu %{
        set-option buffer lsp_servers %{
            [nu]
            args = ["--lsp"]
            root_globs = [".jj", ".git"]
        }
    }
    lsp-enable
    lsp-auto-signature-help-enable

    map global user l ':enter-user-mode lsp<ret>' -docstring 'Enter LSP mode'
    map global goto d '<esc>:lsp-definition<ret>' -docstring 'Go to definition'
    map global goto r '<esc>:lsp-references<ret>' -docstring 'Find references'
    map global goto i '<esc>:lsp-implementation<ret>' -docstring 'Go to implementation'

    define-command lsp-manual-completion -docstring 'Request LSP completion' %{
        set-option window lsp_completion_trigger nop
        lsp-completion
        unset-option window lsp_completion_trigger
    }
    map global insert <c-space> '<a-;>:lsp-manual-completion<ret>' -docstring 'Request LSP completion'

}
